[build]
	publish = "dist/static"
	command = "npm run jam"

[[redirects]]
	from = "/*"
	to = "/"
	status = 301

[[plugins]]
	package = "@algolia/netlify-plugin-crawler"  	
		[plugins.inputs]
  			branches = ['release']



# NOTES:

# SCULLY - deploy to Netlyfy --> only worked in prev img verion: "Ubuntu Xenial 16.04"
# (Site Setings > Build & deploiy > Build image selection)

# DEPLOY MINUTES --> Don't exceed the monthly available "deploy minutes" for free,
# setting up the production branch to "release" instead of "master" and
# you can also use the plugin "Deployment hours" to block deployment if outta free minutes.
